version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks
      POSTGRES_HOST_AUTH_METHOD: trust # Disable password authentication for simplicity
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    # DO NOT mount host node_modules
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      VITE_HOST: 0.0.0.0
    command: ["npm", "run", "dev", "--", "--host"]
